### ISSUE TITLE
Flag --base_folder must have a value other than None.

### ISSUE THREAD

**Issue by joiellantero** [google/nerfies#50]
I encountered this issue when I ran `python train.py --data_dir $DATASET_PATH --base_folder $EXPERIMENT_PATH --gin_configs configs/test_vrig.gin`.  Below is the error log. What can I try to solve this? Thanks!

```shell
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    jax.config.parse_flags_with_absl()
  File "/home/jllantero/miniconda3/envs/nerfies/lib/python3.8/site-packages/jax/_src/config.py", line 161, in parse_flags_with_absl
    absl.flags.FLAGS(jax_argv, known_only=True)
  File "/home/jllantero/miniconda3/envs/nerfies/lib/python3.8/site-packages/absl/flags/_flagvalues.py", line 673, in __call__
    self.validate_all_flags()
  File "/home/jllantero/miniconda3/envs/nerfies/lib/python3.8/site-packages/absl/flags/_flagvalues.py", line 533, in validate_all_flags
    self._assert_validators(all_validators)
  File "/home/jllantero/miniconda3/envs/nerfies/lib/python3.8/site-packages/absl/flags/_flagvalues.py", line 568, in _assert_validators
    raise _exceptions.IllegalFlagValueError('\n'.join(messages))
absl.flags._exceptions.IllegalFlagValueError: flag --base_folder=None: Flag --base_folder must have a value other than None.
```

**Comment by zhengxyun** [comment]
I got the same error message  while training. Have you solved?

**Comment by blackz5** [comment]
Same issue here. Any solutions to this yet?

**Comment by asinghka** [comment]
Same issue here. Any solutions yet?

**Comment by xh-liu-tech** [comment]
Just replacing the `None` in train.py (46) with an arbitrary value fixes the problem for me.

`flags.DEFINE_string('base_folder', 'base_folder', 'where to store ckpts and logs')`

**Comment by joiellantero** [comment]
> Just replacing the `None` in train.py (46) with an arbitrary value fixes the problem for me.
> 
> `flags.DEFINE_string('base_folder', 'base_folder', 'where to store ckpts and logs')`

This solved the issue, thank you!
