### ISSUE TITLE
AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'

### ISSUE THREAD

**Issue by panxiaolong110** [google/nerfies#64]
Traceback (most recent call last):
  File "D:/VS/python/nerfies-main/train.py", line 23, in <module>
    from flax import jax_utils
  File "D:\RJ\A\python3.8\lib\site-packages\flax\__init__.py", line 36, in <module>
    from . import core
  File "D:\RJ\A\python3.8\lib\site-packages\flax\core\__init__.py", line 15, in <module>
    from .axes_scan import broadcast
  File "D:\RJ\A\python3.8\lib\site-packages\flax\core\axes_scan.py", line 17, in <module>
    import jax
  File "D:\RJ\A\python3.8\lib\site-packages\jax\__init__.py", line 109, in <module>
    from .experimental.maps import soft_pmap
  File "D:\RJ\A\python3.8\lib\site-packages\jax\experimental\maps.py", line 25, in <module>
    from .. import numpy as jnp
  File "D:\RJ\A\python3.8\lib\site-packages\jax\numpy\__init__.py", line 16, in <module>
    from . import fft
  File "D:\RJ\A\python3.8\lib\site-packages\jax\numpy\fft.py", line 17, in <module>
    from jax._src.numpy.fft import (
  File "D:\RJ\A\python3.8\lib\site-packages\jax\_src\numpy\fft.py", line 19, in <module>
    from jax import lax
  File "D:\RJ\A\python3.8\lib\site-packages\jax\lax\__init__.py", line 332, in <module>
    from jax._src.lax.fft import (
  File "D:\RJ\A\python3.8\lib\site-packages\jax\_src\lax\fft.py", line 145, in <module>
    xla.backend_specific_translations['cpu'][fft_p] = pocketfft.pocketfft
AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'

**Comment by CASIATumingfei** [comment]
Hi, I met the same error with you. Did you fix it?

**Comment by JYC1012** [comment]
me too
